# Metadata
site_name: Titan Docs
site_description: "Documentation for Titan Embeds"
site_author: "Jelle Z."

# Theming
theme:
  name: "material"
  font:
    text: "Whitney"
    code: "Ubuntu Mono"
  logo: "img/logo.svg"

# Extensions
markdown_extensions:
  - admonition
  - footnotes

# Import
extra_css:
  - "style.css"
extra_javascript:
  - "script.js"

# Repository
repo_url: "https://github.com/TitanEmbeds/Titan"
edit_uri: ""

# Copyright
copyright: "Licensed under the GNU Affero General Public License v3.0"
