# Metadata
site_name: Titan Docs
site_description: "Documentation for Titan Embeds"
site_author: "Jelle Z."

# Theming
theme:
  name: "material"
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: "Whitney"
    code: "Ubuntu Mono"
  logo: "img/logo.svg"

# Extensions
markdown_extensions:
  - admonition
  - footnotes

# Import
extra_css:
  - "style.css"
extra_javascript:
  - "script.js"

# Repository
repo_url: "https://github.com/TitanEmbeds/TitanDocs/"
edit_uri: "edit/master/docs/"

# social

extra:
  social:
    - type: 'github'
      link: 'https://github.com/TitanEmbeds'
    - type: 'discord'
      link: 'https://discordapp.com/invite/pFDDtcN'

# Copyright
copyright: "Licensed under the GNU Affero General Public License v3.0"
